\version "2.24.2"

tempoH-VIIa = \tempoMarkup "Presto"
tempoH-VIIb = \tempoMarkup "Andante"
tempoH-VIIc = \tempoMarkup "Adagio"
tempoH-VIId = \tempoMarkup "Allabreve"
tempoH-VIIe = \tempoMarkup "Adagio"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
