\version "2.24.2"

tempoD-II-XVILaudate = \tempoMarkup "Allegro"
tempoD-II-XVISit = \tempoMarkup "Larghetto"
tempoD-II-XVISolis = \tempoMarkup "Vivace"
tempoD-II-XVIQuis = \tempoMarkup "[no tempo]"
  tempoD-II-XVIHumilia = \tempoMarkup "Adagio"
  tempoD-II-XVITerra = \tempoMarkup "[Grave]"
tempoD-II-XVISuscitans = \tempoMarkup "Allegro"
tempoD-II-XVIHabitare = \tempoMarkup "Allegretto"
tempoD-II-XVIGloria = \tempoMarkup "Adagio"
  tempoD-II-XVISicut = \tempoMarkup "Allegretto"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
