\version "2.24.2"

tempoF-III-IISalve = \tempoMarkup "Larghetto"
tempoF-III-IIAdTe = \tempoMarkup "Andante"
tempoF-III-IIAdTeB = \tempoMarkup "Adagio"
tempoF-III-IIEia = \tempoMarkup "Vivace"
tempoF-III-IIEtIesum = \tempoMarkup "Largo"
tempoF-III-IIOClemens = \tempoMarkup "Andante"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
