\version "2.24.2"

tempoD-I-IIIDixit = \tempoMarkup "Allegro"
tempoD-I-IIIConfitebor = \tempoMarkup "[Alla breve]"
tempoD-I-IIIBeatus = \tempoMarkup "Allegro"
tempoD-I-IIIPueri = \tempoMarkup "[no tempo]"
tempoD-I-IIILaudate = \tempoMarkup "[no tempo]"
tempoD-I-IIIExitu = \tempoMarkup "[no tempo]"
tempoD-I-IIIMagnificat = \tempoMarkup "Adagio"
  tempoD-I-IIIMagnificatB = \tempoMarkup "Allegro"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
