\version "2.24.2"

tempoC-II-VIIIPlacare = \tempoMarkup "Larghetto"
tempoC-II-VIIIEtVos = \tempoMarkup "Andante"
tempoC-II-VIIIAmen = \tempoMarkup "[Allegro]"
tempoC-II-VIIIAmenB = \tempoMarkup "Adagio"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
